# Generated by Django 3.2.5 on 2021-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=100),
        ),
    ]
