# Generated by Django 3.2.5 on 2021-08-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0006_alter_comment_commenter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='photo_id',
        ),
    ]
