# Generated by Django 3.2.5 on 2021-08-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0007_rename_photo_comment_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
